default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV["RAILS_MAX_THREADS"] || 5 %>
  host: localhost

development:
  <<: *default
  database: laurel_and_amit_development
  username: agulati

test:
  <<: *default
  database: laurel_and_amit_test

production:
  <<: *default
  database: laurel_and_amit
  url: <%= ENV["DATABASE_URL"] %>
